language: node_js
node_js:
  - "0.11"
before_script:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli bower
  - bower install
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
script: "grunt check"
